/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_Logger */

#ifndef _Included_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_Logger
#define _Included_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_Logger
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
