/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_NativeAPI */

#ifndef _Included_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_NativeAPI
#define _Included_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_NativeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_NativeAPI
 * Method:    getVersionInfo
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_00024NativeAPI_getVersionInfo
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_NativeAPI
 * Method:    getBuildInfo
 * Signature: (Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_00024NativeAPI_getBuildInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_NativeAPI
 * Method:    setLoggingHandler
 * Signature: (Lcom/muldersoft/dynaudnorm/JDynamicAudioNormalizer/Logger;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_00024NativeAPI_setLoggingHandler
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_NativeAPI
 * Method:    createInstance
 * Signature: (IIIIDDDDZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_00024NativeAPI_createInstance
  (JNIEnv *, jclass, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jboolean, jboolean, jboolean);

/*
 * Class:     com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_NativeAPI
 * Method:    destroyInstance
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer_00024NativeAPI_destroyInstance
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
