/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muldersoft_dynaudnorm_JDynamicAudioNormalizer */

#ifndef _Included_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer
#define _Included_com_muldersoft_dynaudnorm_JDynamicAudioNormalizer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
