/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DynamicAudioNormalizer_JDynamicAudioNormalizer */

#ifndef _Included_DynamicAudioNormalizer_JDynamicAudioNormalizer
#define _Included_DynamicAudioNormalizer_JDynamicAudioNormalizer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
