/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DynamicAudioNormalizer_JDynamicAudioNormalizer_NativeAPI */

#ifndef _Included_DynamicAudioNormalizer_JDynamicAudioNormalizer_NativeAPI
#define _Included_DynamicAudioNormalizer_JDynamicAudioNormalizer_NativeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DynamicAudioNormalizer_JDynamicAudioNormalizer_NativeAPI
 * Method:    getVersionInfo
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_DynamicAudioNormalizer_JDynamicAudioNormalizer_00024NativeAPI_getVersionInfo
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     DynamicAudioNormalizer_JDynamicAudioNormalizer_NativeAPI
 * Method:    getBuildInfo
 * Signature: (Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_DynamicAudioNormalizer_JDynamicAudioNormalizer_00024NativeAPI_getBuildInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     DynamicAudioNormalizer_JDynamicAudioNormalizer_NativeAPI
 * Method:    setLoggingHandler
 * Signature: (LDynamicAudioNormalizer/JDynamicAudioNormalizer/Logger;)Z
 */
JNIEXPORT jboolean JNICALL Java_DynamicAudioNormalizer_JDynamicAudioNormalizer_00024NativeAPI_setLoggingHandler
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
