/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DynamicAudioNormalizer_JDynamicAudioNormalizer_Logger */

#ifndef _Included_DynamicAudioNormalizer_JDynamicAudioNormalizer_Logger
#define _Included_DynamicAudioNormalizer_JDynamicAudioNormalizer_Logger
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
