<style type="text/css">
<!--
  body { font-family: "Times New Roman", Times, serif; color: #000000; background-color: #FFFFFF; }
  p { text-align: justify; }
  tt, pre, code { font-family: Courier New, Courier, mono; background-color: #EDF3F7; padding: 1px; }
  h1:not(.title) { margin-top: 2.25em; }
  h2:not(.author) { margin-top: 2.0em; }
  h3, h4 { margin-top: 1.75em; }
  a { color: #0000BB; text-decoration: none; }
  a:visited { color: #0000BB; text-decoration: none; }
  a:active { color: #0000FF; text-decoration: none; }
  a:hover { color: #0000FF; text-decoration: underline; }
  figure { margin-left: 0em; margin-bottom: 1.66em; }
  figcaption { font-size: 0.8em; font-weight: bold; }
-->
</style>
